openapi: 3.0.0
paths:
  /health:
    get:
      description: Verifies that the API is healthy
      operationId: health
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  timestamp:
                    type: string
                    format: date-time
        "500":
          description: Internal server error
          content:
            application/json:
              schema: &a1
                properties:
                  statusCode:
                    type: number
                    example: 500
                  message:
                    type: string
                    example: Internal Server Error
      summary: API Health Check
      tags:
        - App
  /products:
    post:
      description: Create a product. Auth is required
      operationId: createProduct
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateProductDto"
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductWithoutOrdersDto"
        "401":
          description: Missing or invalid authorization header
          content:
            application/json:
              schema:
                properties:
                  statusCode:
                    type: number
                    example: 401
                  message:
                    type: string
                    example: Missing Authorization Header
        "403":
          description: User has no role assigned or insufficient permissions
          content:
            application/json:
              schema:
                properties:
                  statusCode:
                    type: number
                    example: 403
                  message:
                    type: string
                    example: Insufficient permissions
        "500": &a2
          description: Internal server error
          content:
            application/json:
              schema: *a1
      security:
        - bearer: []
      summary: Create product
      tags: &a3
        - Products
    get:
      description: Search for products given filters
      operationId: searchProducts
      parameters:
        - name: q
          required: false
          in: query
          schema:
            type: string
        - name: category
          required: false
          in: query
          schema:
            type: string
        - name: minPrice
          required: false
          in: query
          schema:
            type: string
        - name: maxPrice
          required: false
          in: query
          schema:
            type: string
        - name: minStock
          required: false
          in: query
          schema:
            type: string
        - name: maxStock
          required: false
          in: query
          schema:
            type: string
        - name: page
          required: false
          in: query
          schema:
            default: 1
            type: string
        - name: limit
          required: false
          in: query
          schema:
            default: 20
            type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductSearchResponseDto"
        "500": *a2
      summary: Get products
      tags: *a3
  /products/{id}:
    get:
      description: Get a single product. A valid id must be used.
      operationId: getProduct
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductWithoutOrdersDto"
        "404":
          description: Missing or invalid authorization header
          content:
            application/json:
              schema:
                properties:
                  statusCode:
                    type: number
                    example: 404
                  message:
                    type: string
                    example: Product does not exist
        "500": *a2
      summary: Get a product
      tags: *a3
    patch:
      description: Update a single product. A valid id must be used. Auth is required.
      operationId: updateProduct
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateProductDto"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductWithoutOrdersDto"
        "401":
          description: Missing or invalid authorization header
          content:
            application/json:
              schema:
                properties:
                  statusCode:
                    type: number
                    example: 401
                  message:
                    type: string
                    example: Missing Authorization Header
        "403":
          description: User has no role assigned or insufficient permissions
          content:
            application/json:
              schema:
                properties:
                  statusCode:
                    type: number
                    example: 403
                  message:
                    type: string
                    example: Insufficient permissions
        "404":
          description: Missing or invalid authorization header
          content:
            application/json:
              schema:
                properties:
                  statusCode:
                    type: number
                    example: 404
                  message:
                    type: string
                    example: Product does not exist
        "500": *a2
      security:
        - bearer: []
      summary: Update a product
      tags: *a3
    delete:
      description: Delete a single product. A valid id must be used. Auth is required.
      operationId: deleteProduct
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductWithoutOrdersDto"
        "401":
          description: Missing or invalid authorization header
          content:
            application/json:
              schema:
                properties:
                  statusCode:
                    type: number
                    example: 401
                  message:
                    type: string
                    example: Missing Authorization Header
        "403":
          description: User has no role assigned or insufficient permissions
          content:
            application/json:
              schema:
                properties:
                  statusCode:
                    type: number
                    example: 403
                  message:
                    type: string
                    example: Insufficient permissions
        "404":
          description: Missing or invalid authorization header
          content:
            application/json:
              schema:
                properties:
                  statusCode:
                    type: number
                    example: 404
                  message:
                    type: string
                    example: Product does not exist
        "500": *a2
      security:
        - bearer: []
      summary: Delete a product
      tags: *a3
  /users:
    post:
      operationId: register
      parameters: []
      responses:
        "201":
          description: ""
        "500": &a4
          description: Internal server error
          content:
            application/json:
              schema: *a1
      security: &a5
        - bearer: []
      tags: &a6
        - Users
    get:
      operationId: searchUsers
      parameters: []
      responses:
        "200":
          description: ""
        "500": *a4
      security: *a5
      tags: *a6
  /users/{id}:
    get:
      operationId: getUser
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: ""
        "500": *a4
      security: *a5
      tags: *a6
  /users/me:
    get:
      operationId: getMyProfile
      parameters: []
      responses:
        "200":
          description: ""
        "500": *a4
      security: *a5
      tags: *a6
    patch:
      operationId: updateMyProfile
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateUserDto"
      responses:
        "200":
          description: ""
        "500": *a4
      security: *a5
      tags: *a6
    delete:
      operationId: deleteMyAccount
      parameters: []
      responses:
        "200":
          description: ""
        "500": *a4
      security: *a5
      tags: *a6
  /carts/me:
    get:
      description: Get the items in your cart
      operationId: getCart
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateCartDto"
        "401": &a7
          description: Missing or invalid authorization header
          content:
            application/json:
              schema:
                properties:
                  statusCode:
                    type: number
                    example: 401
                  message:
                    type: string
                    example: Missing Authorization Header
        "500": &a8
          description: Internal server error
          content:
            application/json:
              schema: *a1
      security: &a9
        - bearer: []
      summary: Get your cart
      tags: &a10
        - Carts
    put:
      description: Update the items in your cart. Add or remove items in your cart
      operationId: updateCart
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateCartDto"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateCartDto"
        "401": *a7
        "500": *a8
      security: *a9
      summary: Update your cart
      tags: *a10
    delete:
      description: "Removes all items from your cart. Note: Cart is automatically
        cleared when an order is placed."
      operationId: clear
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                properties:
                  cart:
                    type: array
                    example: []
        "401": *a7
        "500": *a8
      security: *a9
      summary: Clear your cart
      tags: *a10
  /orders/me:
    post:
      description: Places an order using items from the current user's cart. The cart
        will be processed and converted into an order.
      operationId: createOrder
      parameters: []
      responses:
        "201":
          description: Order successfully created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlaceOrderResponseDto"
        "400":
          description: Cart is empty or invalid
          content:
            application/json:
              schema:
                properties:
                  statusCode:
                    type: number
                    example: 400
                  message:
                    type: string
                    example: Cart is empty. No products to place an order
        "401": &a11
          description: Missing or invalid authorization header
          content:
            application/json:
              schema:
                properties:
                  statusCode:
                    type: number
                    example: 401
                  message:
                    type: string
                    example: Missing Authorization Header
        "403": &a12
          description: User has no role assigned or insufficient permissions
          content:
            application/json:
              schema:
                properties:
                  statusCode:
                    type: number
                    example: 403
                  message:
                    type: string
                    example: Insufficient permissions
        "500": &a13
          description: Internal server error
          content:
            application/json:
              schema: *a1
      security: &a14
        - bearer: []
      summary: Create order from cart
      tags: &a15
        - Orders
    get:
      operationId: searchMyOrders
      parameters:
        - name: dateRange
          required: false
          in: query
          schema:
            $ref: "#/components/schemas/DateRangeDto"
        - name: status
          required: false
          in: query
          schema:
            example: pending
            type: string
            enum:
              - pending
              - cancelled
              - completed
      responses:
        "200":
          description: ""
        "401": *a11
        "403": *a12
        "500": *a13
      security: *a14
      tags: *a15
  /orders:
    get:
      operationId: searchAllOrders
      parameters:
        - name: dateRange
          required: false
          in: query
          schema:
            $ref: "#/components/schemas/DateRangeDto"
        - name: status
          required: false
          in: query
          schema:
            example: pending
            type: string
            enum:
              - pending
              - cancelled
              - completed
      responses:
        "200":
          description: ""
        "401": *a11
        "403": *a12
        "500": *a13
      security: *a14
      tags: *a15
  /orders/{uuid}:
    get:
      operationId: getOrder
      parameters:
        - name: uuid
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: ""
        "401": *a11
        "403": *a12
        "500": *a13
      security: *a14
      tags: *a15
    patch:
      operationId: updateStatus
      parameters:
        - name: uuid
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateOrderDto"
      responses:
        "200":
          description: ""
        "401": *a11
        "403": *a12
        "500": *a13
      security: *a14
      tags: *a15
info:
  title: Nexus API
  description: The backend e-commerce API for Nexus store
  version: "1.0"
  contact: {}
tags:
  - name: nexus
    description: ""
servers: []
components:
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
  schemas:
    CreateProductDto:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        category:
          type: string
        price:
          type: number
        stock:
          type: number
        images:
          type: array
          items:
            type: string
      required:
        - name
        - description
        - category
        - price
        - stock
        - images
    ProductWithoutOrdersDto:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        category:
          type: string
        price:
          type: number
        stock:
          type: number
        images:
          type: array
          items:
            type: string
        createdAt:
          format: date-time
          type: string
        updatedAt:
          format: date-time
          type: string
      required:
        - id
        - name
        - description
        - category
        - price
        - stock
        - images
        - createdAt
        - updatedAt
    ProductSearchResponseDto:
      type: object
      properties:
        products:
          type: array
          items:
            $ref: "#/components/schemas/ProductWithoutOrdersDto"
        page:
          type: number
        perPage:
          type: number
        count:
          type: number
        total:
          type: number
        totalPages:
          type: number
      required:
        - products
        - page
        - perPage
        - count
        - total
        - totalPages
    UpdateProductDto:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        category:
          type: string
        price:
          type: number
        stock:
          type: number
        images:
          type: array
          items:
            type: string
    UpdateUserDto:
      type: object
      properties: {}
    CartItem:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        price:
          type: number
        quantity:
          type: number
        image:
          type: string
      required:
        - id
        - name
        - price
        - quantity
        - image
    UpdateCartDto:
      type: object
      properties:
        cart:
          type: array
          items:
            $ref: "#/components/schemas/CartItem"
      required:
        - cart
    PlaceOrderResponseDto:
      type: object
      properties:
        id:
          type: string
        createdAt:
          format: date-time
          type: string
        updatedAt:
          format: date-time
          type: string
        status:
          type: string
          enum:
            - pending
            - cancelled
            - completed
        total:
          type: string
          description: Order total as a decimal string
        userId:
          type: string
      required:
        - id
        - createdAt
        - updatedAt
        - status
        - total
        - userId
    DateRangeDto:
      type: object
      properties:
        from:
          type: string
          example: 2025-01-01
        to:
          type: string
          example: 2025-12-31
      required:
        - from
        - to
    UpdateOrderDto:
      type: object
      properties: {}
