openapi: 3.0.0
paths:
  /health:
    get:
      description: Verifies that the API is healthy
      operationId: health
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  timestamp:
                    type: string
                    format: date-time
      summary: API Health Check
      tags:
        - App
  /products:
    post:
      description: Create a product. Auth is required
      operationId: createProduct
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateProductDto"
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductWithoutOrdersDto"
      security:
        - bearer: []
      summary: Create product
      tags: &a1
        - Products
    get:
      description: Search for products given filters
      operationId: searchProducts
      parameters:
        - name: q
          required: false
          in: query
          schema:
            type: string
        - name: minPrice
          required: false
          in: query
          schema:
            type: string
        - name: maxPrice
          required: false
          in: query
          schema:
            type: string
        - name: minStock
          required: false
          in: query
          schema:
            type: string
        - name: maxStock
          required: false
          in: query
          schema:
            type: string
        - name: page
          required: false
          in: query
          schema:
            default: 1
            type: string
        - name: limit
          required: false
          in: query
          schema:
            default: 20
            type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductSearchResponseDto"
      summary: Get products
      tags: *a1
  /products/{uuid}:
    get:
      description: Get a single product. A valid uuid must be used.
      operationId: getProduct
      parameters:
        - name: uuid
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductWithoutOrdersDto"
      summary: Get a product
      tags: *a1
    patch:
      description: Update a single product. A valid uuid must be used. Auth is required.
      operationId: updateProduct
      parameters:
        - name: uuid
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateProductDto"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductWithoutOrdersDto"
      security:
        - bearer: []
      summary: Update a product
      tags: *a1
    delete:
      description: Delete a single product. A valid uuid must be used. Auth is required.
      operationId: deleteProduct
      parameters:
        - name: uuid
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductWithoutOrdersDto"
      security:
        - bearer: []
      summary: Delete a product
      tags: *a1
  /users:
    post:
      operationId: register
      parameters: []
      responses:
        "201":
          description: ""
      tags: &a2
        - Users
    get:
      operationId: findAll
      parameters: []
      responses:
        "200":
          description: ""
      tags: *a2
  /users/{id}:
    get:
      operationId: findOne
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: ""
      tags: *a2
  /users/me:
    get:
      operationId: getMyProfile
      parameters: []
      responses:
        "200":
          description: ""
      tags: *a2
    patch:
      operationId: update
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateUserDto"
      responses:
        "200":
          description: ""
      tags: *a2
    delete:
      operationId: remove
      parameters: []
      responses:
        "200":
          description: ""
      tags: *a2
  /carts:
    get:
      operationId: getCart
      parameters: []
      responses:
        "200":
          description: ""
      tags: &a3
        - Carts
    put:
      operationId: updateCart
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateCartDto"
      responses:
        "200":
          description: ""
      tags: *a3
    delete:
      operationId: clear
      parameters: []
      responses:
        "200":
          description: ""
      tags: *a3
  /orders:
    post:
      operationId: create
      parameters: []
      responses:
        "201":
          description: ""
      tags: &a4
        - Orders
    get:
      operationId: search
      parameters: []
      responses:
        "200":
          description: ""
      tags: *a4
  /orders/{uuid}:
    get:
      operationId: findOne
      parameters:
        - name: uuid
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: ""
      tags: *a4
    patch:
      operationId: updateStatus
      parameters:
        - name: uuid
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateOrderDto"
      responses:
        "200":
          description: ""
      tags: *a4
info:
  title: Nexus API
  description: The backend e-commerce API for Nexus store
  version: "1.0"
  contact: {}
tags:
  - name: nexus
    description: ""
servers: []
components:
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
  schemas:
    CreateProductDto:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        category:
          type: string
        price:
          type: number
        stock:
          type: number
        images:
          type: array
          items:
            type: string
      required:
        - name
        - description
        - category
        - price
        - stock
        - images
    ProductWithoutOrdersDto:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        category:
          type: string
        price:
          type: number
        stock:
          type: number
        images:
          type: array
          items:
            type: string
        createdAt:
          format: date-time
          type: string
        updatedAt:
          format: date-time
          type: string
      required:
        - id
        - name
        - description
        - category
        - price
        - stock
        - images
        - createdAt
        - updatedAt
    ProductSearchResponseDto:
      type: object
      properties:
        products:
          type: array
          items:
            $ref: "#/components/schemas/ProductWithoutOrdersDto"
        page:
          type: number
        perPage:
          type: number
        count:
          type: number
        total:
          type: number
        totalPages:
          type: number
      required:
        - products
        - page
        - perPage
        - count
        - total
        - totalPages
    UpdateProductDto:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        category:
          type: string
        price:
          type: number
        stock:
          type: number
        images:
          type: array
          items:
            type: string
    UpdateUserDto:
      type: object
      properties: {}
    UpdateCartDto:
      type: object
      properties: {}
    UpdateOrderDto:
      type: object
      properties: {}
