name: CI Pipeline
run-name: "CI Run for ${{ github.event.head_commit.message }}"

on:
  push:
    branches:
      - main
      - feat/*
      - fix/*
      - test/*

jobs:
  unit-integration-tests:
    runs-on: ubuntu-latest
    name: Run ${{ matrix.test-type }} tests
    
    strategy:
      matrix:
        test-type: [unit, integration]
    
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Pull test images
        if: matrix.test-type == 'integration'
        run: docker pull postgres:18 && docker pull redis:8.4.0

      - name: Run ${{ matrix.test-type }} tests
        run: pnpm test:api:${{ matrix.test-type }}

  e2e-tests:
    runs-on: ubuntu-latest
    name: Run e2e tests

    env:
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
      FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}

    services:
      postgres:
        image: postgres:18
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.DATABASE_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DATABASE_NAME }}
      redis:
        image: redis:8.4.0
        ports:
          - 6379:6379
    
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run test database migrations
        run: pnpm run:migration

      - name: Run e2e tests
        run: pnpm test:api:e2e

  build-images:
    needs: [unit-integration-tests, e2e-tests]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image-type: [api, web]

    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Build production artifacts
        run: scripts/build-api.sh

      - name: Build ${{ matrix.image-type }} docker image
        run: |
          docker build \
            -t nexus-${{ matrix.image-type }}:${GITHUB_SHA::7} \
            -f packages/${{ matrix.image-type }}/Dockerfile .

      - name: Save Docker image to tar
        run: docker save ${{ matrix.image-type }}:latest -o ${{ matrix.image-type }}-image.tar
      
      - name: Compress the image
        run: gzip ${{ matrix.image-type }}-image.tar
      
      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-${{ matrix.image-type }}
          path: ${{ matrix.image-type }}-image.tar.gz
          retention-days: 7